# -----------------------------------------------
# dbt Project Configuration

name: 'eurowag'
version: '1.0.0'
config-version: 2

dbt-cloud:
  project-id: 70471823522831

profile: 'eurowag'

# -----------------------------------------------
# File paths

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# -----------------------------------------------
# Build and clean targets

target-path: "target"     # SQL complied files here
clean-targets:
  - "target"
  - "dbt_packages"

# -----------------------------------------------
# Model configuration

# -----------------------------------------------
# Model configuration

models:
  eurow_demo:
    stg:                    # Bronze layer
      +materialized: table  # Full load
      +schema: dbt_abenes_stg
      +tags: ["bronze", "stage"]
    cln:                    # Silver layer
      +materialized: table
      +schema: dbt_abenes_cln
      +tags: ["silver", "clean"]
    rpt:                    # Gold layer
      +materialized: table
      +schema: dbt_abenes_rpt
      +tags: ["rpt", "gold"]

# -----------------------------------------------
# Snapshot configuration

snapshots:
  cln:
    +schema: snapshots_cln
    +target_database: ewdemo
  rpt:
    +schema: snapshots_rpt
    +target_database: ewdemo
